### ISSUE TITLE
Support Symfony 6.0

### ISSUE THREAD

**Issue by tm1000** [Elendev/composer-push#62]
~~Symfony 6 is only supported in `friendsofphp/php-cs-fixer` 3.4.0, 3.4.0 does not support Symfony 3 (This library does). Additionally `friendsofphp/php-cs-fixer` 3.5.0 drops Symfony 4. Determination is this library should be on `friendsofphp/php-cs-fixer` 3.5.0.~~

~~However! `friendsofphp/php-cs-fixer` 3.5.0 requires `composer/xdebug-handler` 3.0.1 but `composer/composer` 2.2.6 (Latest) itself does not currently require `composer/xdebug-handler` 3.0.1 (its in main but not in a release yet) thus the two packages are incompatible at this time. Until `composer/composer` main branch gets tagged in a release.~~

I was able to find a compatible set of requirements without having to wait for `composer/composer`

See https://github.com/Elendev/composer-push/pull/63

**Comment by Elendev** [comment]
Hello @tm1000 thanks for your contribution, I just released the version 1.0.0 with support for Symfony 6 👍
